name: on-schedule
run-name: on schedule

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-citations:
    uses: ./.github/workflows/update-citations.yaml
    with:
      open-pr: true
